-- MySQL Script generated by MySQL Workbench
-- Sat Dec  3 22:50:35 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sofisticao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sofisticao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sofisticao` DEFAULT CHARACTER SET utf8 ;
USE `sofisticao` ;

-- -----------------------------------------------------
-- Table `sofisticao`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sofisticao`.`CLIENTE` (
  `ID_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` VARCHAR(45) NOT NULL,
  `LOGIN` VARCHAR(45) NOT NULL,
  `SENHA` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`ID_CLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sofisticao`.`ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sofisticao`.`ANIMAL` (
  `ID_ANIMAL` INT NOT NULL AUTO_INCREMENT,
  `NOME_ANIMAL` VARCHAR(45) NOT NULL,
  `RACA` VARCHAR(45) NULL,
  `DATA_NASC` DATE NOT NULL,
  `ESPECIE` VARCHAR(45) NOT NULL,
  `SEXO_ANIMAL` CHAR(1) NULL,
  `CLIENTE_ID_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`ID_ANIMAL`),  
    FOREIGN KEY (`CLIENTE_ID_CLIENTE`)
    REFERENCES `sofisticao`.`CLIENTE` (`ID_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sofisticao`.`VACINA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sofisticao`.`VACINA` (
  `ID_VACINA` INT NOT NULL AUTO_INCREMENT,
  `NOME_VACINA` VARCHAR(45) NOT NULL,
  `PERIODICIDADE` DOUBLE NOT NULL,
  `TIPO_VACINA` VARCHAR(45) NULL,
  `DESC_VACINA` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_VACINA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sofisticao`.`VACINAS_ANIMAL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sofisticao`.`VACINAS_ANIMAL` (
  `ID_VACINA_ANIMAL` INT NOT NULL AUTO_INCREMENT,
  `DATA_VACINACAO` DATE NOT NULL,
  `OBSERVACOES` VARCHAR(125) NULL,
  `VACINA_ID_VACINA` INT NOT NULL,
  `VACINA_ID_ANIMAL` INT NOT NULL,
  PRIMARY KEY (`ID_VACINA_ANIMAL`),  
    FOREIGN KEY (`VACINA_ID_VACINA`)
    REFERENCES `sofisticao`.`VACINA` (`ID_VACINA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,  
    FOREIGN KEY (`VACINA_ID_ANIMAL`)
    REFERENCES `sofisticao`.`ANIMAL` (`ID_ANIMAL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
